### ISSUE TITLE
clicking right arrow button and then scrolling bug

### ISSUE THREAD

**Issue by Jeluxe** [medyo/hackertab.dev#112]
so assuming someone has more than 4 displayed cards and then you click on the right arrow button and then you try to scroll on one of the displayed cards then the left arrow button suddenly disappears but if you still have one or more cards from the right you can click on the right arrow and if it's returning the left arrow but then again if you try to scroll the left arrow button disappears and if you don't have any more cards from the right so then even if you click on the right arrow button, the left arrow button won't show anymore, move to cards from the left unless you refresh the page

using the website and Microsoft Edge

**Comment by medyo** [comment]
@Jeluxe We just released a new web version, can you check now?

**Comment by Jeluxe** [comment]
yes, I just checked the website in this URL: https://now.hackertab.dev/ 
and yet the bug still occurs.

**Comment by Jeluxe** [comment]
well for some reason when you scrolling always the right arrow button appears and the left not,
well few ways to temporarily fix it are to either press the left or right keycaps on the keyboard or to use shift + scrolling for horizontal scrolling
